// Codegen for `src/plugins/_generated/{metas,registrations,server-bindings}.ts`.
//
// Why: adding a built-in plugin used to require touching 3 host
// barrels (`src/plugins/{metas,index,server}.ts`) on top of the
// plugin-local files. Forgetting one was a silent class of bugs
// (#1141 caught presentForm scope mismatch the same way). This
// script reads `src/plugins/<name>/{meta.ts,definition.ts,index.ts}`
// and emits the mechanical bits, so plugin authors edit only their
// own directory.
//
// Conventions the codegen relies on:
//
//   - Every plugin lives in `src/plugins/<name>/`.
//   - Meta lives in `<dir>/meta.ts` OR `<dir>/<role>Meta.ts`
//     (multi-meta plugin like scheduler — calendar / automations).
//     Each meta module exports `export const META = ...`.
//   - Registration lives in `<dir>/index.ts`. Single-entry plugins
//     export `REGISTRATION`; multi-entry plugins (scheduler) export
//     `REGISTRATIONS` (array).
//   - MCP definition lives in `<dir>/definition.ts` OR
//     `<dir>/<role>Definition.ts`, default-exported.
//   - A plugin emits a server binding only when its META declares
//     BOTH `apiNamespace` and `mcpDispatch`. Plugins without those
//     fields (editImages / generateImage — image namespace shared
//     with host) live in `_extras.ts` instead.
//
// Modes:
//   - default: rewrite `src/plugins/_generated/*.ts` from disk
//   - `--check`: rewrite into memory and `process.exit(1)` if any
//     output differs from disk. CI uses this to fail PRs that added
//     a plugin directory without re-running the codegen.

import { mkdirSync, readFileSync, readdirSync, statSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import path from "node:path";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(SCRIPT_DIR, "..");
const PLUGINS_DIR = path.join(REPO_ROOT, "src", "plugins");
const GENERATED_DIR = path.join(PLUGINS_DIR, "_generated");

const HEADER = "// AUTO-GENERATED by `scripts/codegen-plugin-barrels.ts`. DO NOT EDIT.\n// Run `yarn plugins:codegen` after adding/removing/renaming a plugin.\n";

interface MetaEntry {
  /** plugin directory name, e.g. "accounting" or "scheduler" */
  pluginDir: string;
  /** meta source file relative to plugins dir, e.g. "accounting/meta.ts" */
  file: string;
  /** identifier used in generated code, e.g. "accountingMeta" or "schedulerCalendarMeta" */
  importName: string;
  /** import path from `_generated/*.ts`, e.g. "../accounting/meta" */
  importPath: string;
  /** value from `apiNamespace: "..."` in source, or null */
  apiNamespace: string | null;
  /** value from `mcpDispatch: "..."` in source, or null */
  mcpDispatch: string | null;
}

interface DefEntry {
  pluginDir: string;
  file: string;
  importName: string;
  importPath: string;
  /** "calendar" / "automations" / "" — the part before "Definition.ts" */
  role: string;
}

interface RegistrationEntry {
  pluginDir: string;
  /** "REGISTRATION" or "REGISTRATIONS" */
  exportName: string;
  importName: string;
  importPath: string;
}

const SCRIPT_NAME = path.basename(fileURLToPath(import.meta.url));

function listPluginDirs(): string[] {
  return readdirSync(PLUGINS_DIR)
    .filter((name) => !name.startsWith("_") && !name.endsWith(".ts"))
    .filter((name) => {
      const stat = statSync(path.join(PLUGINS_DIR, name));
      return stat.isDirectory();
    })
    .sort();
}

function camelize(parts: readonly string[]): string {
  return parts
    .map((part, index) => (index === 0 ? part : part.charAt(0).toUpperCase() + part.slice(1)))
    .join("");
}

/** Pull a plain string-literal value for a top-level meta field from
 *  source. Skips fields inside nested objects (e.g.
 *  `apiRoutes.create.path: "/foo"`). Tight regex: matches
 *  `apiNamespace: "value"` only when it appears immediately under
 *  `definePluginMeta({` indentation (2 spaces). Good enough for the
 *  current convention; falls back to null when not present. */
function extractTopLevelString(source: string, field: string): string | null {
  const re = new RegExp(`^\\s{2}${field}:\\s*"([^"]+)"`, "m");
  const match = re.exec(source);
  return match ? match[1] : null;
}

function findMetas(pluginDir: string): MetaEntry[] {
  const dir = path.join(PLUGINS_DIR, pluginDir);
  const files = readdirSync(dir);
  const metaFiles = files.filter((file) => file === "meta.ts" || (file.endsWith("Meta.ts") && file !== "Meta.ts"));
  return metaFiles.map((file) => {
    const source = readFileSync(path.join(dir, file), "utf8");
    const role = file === "meta.ts" ? "" : file.replace(/Meta\.ts$/, "");
    const importName = role === "" ? `${pluginDir}Meta` : camelize([pluginDir, role, "meta"]);
    return {
      pluginDir,
      file: `${pluginDir}/${file}`,
      importName,
      importPath: `../${pluginDir}/${file.replace(/\.ts$/, "")}`,
      apiNamespace: extractTopLevelString(source, "apiNamespace"),
      mcpDispatch: extractTopLevelString(source, "mcpDispatch"),
    };
  });
}

function findDefinitions(pluginDir: string): DefEntry[] {
  const dir = path.join(PLUGINS_DIR, pluginDir);
  const files = readdirSync(dir);
  const defFiles = files.filter((file) => file === "definition.ts" || (file.endsWith("Definition.ts") && file !== "Definition.ts"));
  return defFiles.map((file) => {
    const role = file === "definition.ts" ? "" : file.replace(/Definition\.ts$/, "");
    const importName = role === "" ? `${pluginDir}Def` : camelize([pluginDir, role, "def"]);
    return {
      pluginDir,
      file: `${pluginDir}/${file}`,
      importName,
      importPath: `../${pluginDir}/${file.replace(/\.ts$/, "")}`,
      role,
    };
  });
}

function findRegistration(pluginDir: string): RegistrationEntry | null {
  const indexPath = path.join(PLUGINS_DIR, pluginDir, "index.ts");
  let source: string;
  try {
    source = readFileSync(indexPath, "utf8");
  } catch {
    return null;
  }
  const exportsRegistrations = /^export const REGISTRATIONS\b/m.test(source);
  const exportsRegistration = /^export const REGISTRATION\b/m.test(source);
  if (!exportsRegistrations && !exportsRegistration) return null;
  const exportName = exportsRegistrations ? "REGISTRATIONS" : "REGISTRATION";
  const importName = exportsRegistrations ? `${pluginDir}Registrations` : `${pluginDir}Registration`;
  return {
    pluginDir,
    exportName,
    importName,
    importPath: `../${pluginDir}`,
  };
}

interface ScanResult {
  metas: MetaEntry[];
  definitions: DefEntry[];
  registrations: RegistrationEntry[];
}

function scanPlugins(): ScanResult {
  const metas: MetaEntry[] = [];
  const definitions: DefEntry[] = [];
  const registrations: RegistrationEntry[] = [];
  for (const pluginDir of listPluginDirs()) {
    metas.push(...findMetas(pluginDir));
    definitions.push(...findDefinitions(pluginDir));
    const reg = findRegistration(pluginDir);
    if (reg) registrations.push(reg);
  }
  return { metas, definitions, registrations };
}

function emitMetasBarrel(metas: readonly MetaEntry[]): string {
  const imports = metas.map((meta) => `import { META as ${meta.importName} } from "${meta.importPath}";`).join("\n");
  const arrayBody = metas.map((meta) => `  ${meta.importName},`).join("\n");
  return [
    HEADER,
    'import type { PluginMeta } from "../meta-types";',
    "",
    imports,
    "",
    "/** All plugin METAs the codegen discovered under `src/plugins/<name>/{meta,*Meta}.ts`.",
    " *  Combined with `_extras` (if any) inside `src/plugins/metas.ts`. */",
    "export const GENERATED_PLUGIN_METAS = [",
    arrayBody,
    "] as const satisfies readonly PluginMeta[];",
    "",
    "export type GeneratedPluginMetas = typeof GENERATED_PLUGIN_METAS;",
    "",
  ].join("\n");
}

function emitRegistrationsBarrel(registrations: readonly RegistrationEntry[]): string {
  const imports = registrations.map((reg) => `import { ${reg.exportName} as ${reg.importName} } from "${reg.importPath}";`).join("\n");
  const arrayBody = registrations
    .map((reg) => (reg.exportName === "REGISTRATIONS" ? `  ...${reg.importName},` : `  ${reg.importName},`))
    .join("\n");
  return [
    HEADER,
    'import type { PluginRegistration } from "../../tools/types";',
    "",
    imports,
    "",
    "/** All plugin registrations the codegen discovered under `src/plugins/<name>/index.ts`.",
    " *  Single-entry plugins export `REGISTRATION`; multi-entry plugins (scheduler)",
    " *  export `REGISTRATIONS` and are spread. Combined with `_extras` inside",
    " *  `src/plugins/index.ts`. */",
    "export const GENERATED_PLUGIN_REGISTRATIONS: readonly PluginRegistration[] = [",
    arrayBody,
    "];",
    "",
  ].join("\n");
}

interface BindingPair {
  def: DefEntry;
  /** The META providing `apiNamespace + mcpDispatch` for this binding's
   *  endpoint. For paired files (calendarDefinition + calendarMeta) this
   *  is the same role's META; if no per-role META has the dispatch info
   *  but a sibling does, we use the sibling (scheduler/automations case). */
  meta: MetaEntry;
}

/** Find which META owns this definition's MCP dispatch URL. Pairs by
 *  role (calendarDefinition.ts ↔ calendarMeta.ts); falls back to any
 *  sibling META with `apiNamespace + mcpDispatch` set when the paired
 *  meta is toolName-only (scheduler/automationsMeta). Returns null
 *  when no sibling provides a dispatchable META — those plugins live
 *  in `_extras.ts`. */
function pairBinding(def: DefEntry, allMetas: readonly MetaEntry[]): MetaEntry | null {
  const dirMetas = allMetas.filter((meta) => meta.pluginDir === def.pluginDir);
  const exact = dirMetas.find((meta) => {
    const metaRole = meta.file.endsWith("/meta.ts") ? "" : meta.file.replace(/^.*\//, "").replace(/Meta\.ts$/, "");
    return metaRole === def.role;
  });
  if (exact && exact.apiNamespace && exact.mcpDispatch) return exact;
  const sibling = dirMetas.find((meta) => meta.apiNamespace !== null && meta.mcpDispatch !== null);
  return sibling ?? null;
}

function emitServerBindingsBarrel(definitions: readonly DefEntry[], metas: readonly MetaEntry[]): string {
  const pairs: BindingPair[] = [];
  for (const def of definitions) {
    const meta = pairBinding(def, metas);
    if (meta) pairs.push({ def, meta });
  }
  // Imports — defs first, then any meta we reference. Dedup metas
  // by importPath since multiple defs in the same dir may share one.
  const defImports = pairs.map(({ def }) => `import ${def.importName} from "${def.importPath}";`);
  const seenMetas = new Set<string>();
  const metaImports: string[] = [];
  for (const { meta } of pairs) {
    if (seenMetas.has(meta.importName)) continue;
    seenMetas.add(meta.importName);
    metaImports.push(`import { META as ${meta.importName} } from "${meta.importPath}";`);
  }
  const rows = pairs.map(({ def, meta }) => `  { def: ${def.importName}, endpoint: mcpEndpoint(${meta.importName}) },`).join("\n");
  return [
    HEADER,
    'import type { ServerPluginBinding } from "../server-bindings-types";',
    'import { mcpEndpoint } from "../server-bindings-types";',
    "",
    defImports.join("\n"),
    metaImports.join("\n"),
    "",
    "/** All plugin MCP bindings the codegen discovered for plugins whose META declares",
    " *  both `apiNamespace` and `mcpDispatch`. Plugins without those fields (image plugins,",
    " *  external npm plugins) live in `_extras.ts`. Combined inside `src/plugins/server.ts`. */",
    "export const GENERATED_SERVER_BINDINGS: readonly ServerPluginBinding[] = [",
    rows,
    "];",
    "",
  ].join("\n");
}

function ensureGeneratedDir(): void {
  mkdirSync(GENERATED_DIR, { recursive: true });
}

interface OutputFile {
  filename: string;
  content: string;
}

function buildOutputs(scan: ScanResult): OutputFile[] {
  return [
    { filename: "metas.ts", content: emitMetasBarrel(scan.metas) },
    { filename: "registrations.ts", content: emitRegistrationsBarrel(scan.registrations) },
    { filename: "server-bindings.ts", content: emitServerBindingsBarrel(scan.definitions, scan.metas) },
  ];
}

function readExisting(filename: string): string | null {
  try {
    return readFileSync(path.join(GENERATED_DIR, filename), "utf8");
  } catch {
    return null;
  }
}

function main(): void {
  const checkMode = process.argv.includes("--check");
  const scan = scanPlugins();
  const outputs = buildOutputs(scan);
  ensureGeneratedDir();
  let drift = false;
  for (const { filename, content } of outputs) {
    const existing = readExisting(filename);
    if (existing === content) continue;
    if (checkMode) {
      drift = true;
      process.stderr.write(`[${SCRIPT_NAME}] drift in ${filename}\n`);
      continue;
    }
    writeFileSync(path.join(GENERATED_DIR, filename), content, "utf8");
    process.stdout.write(`[${SCRIPT_NAME}] wrote ${filename}\n`);
  }
  if (checkMode && drift) {
    process.stderr.write(`[${SCRIPT_NAME}] one or more generated files are out of date — run \`yarn plugins:codegen\` and commit the result.\n`);
    process.exit(1);
  }
  if (!checkMode) {
    process.stdout.write(`[${SCRIPT_NAME}] discovered ${scan.metas.length} metas, ${scan.registrations.length} registrations, ${scan.definitions.length} definitions\n`);
  }
}

main();
